export const UPDATE_PRODUCTS = "UPDATES_PRODUCTS"; 

export const ADD_PRODUCT_TO_LIST = "ADD_PRODUCT_TO_LIST";
export const UPDATE_PRODUCT_IN_LIST = "UPDATE_PRODUCT_IN_LIST";
export const DELETE_PRODUCT_FROM_LIST = "DELETE_PRODUCT_FROM_LIST";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_SHOW_CART = "SET_SHOW_CART";
